"""Cache existing catalog photos as same-origin assets (no database needed).
Usage: python3 scripts/cache_photos.py /tmp/bias-photo-catalog.json
"""
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
import json
import subprocess
import sys
import tempfile
import urllib.request
import time

root = Path(__file__).resolve().parent.parent
output = root / 'src/assets/idols'
output.mkdir(parents=True, exist_ok=True)
items = json.loads(Path(sys.argv[1]).read_text())
sources = sorted(set(item['img'] for item in items))

def cache(source):
    import hashlib
    destination = output / (hashlib.sha256(source.encode()).hexdigest()[:16] + '.jpg')
    if destination.exists():
        return source, destination.relative_to(root).as_posix(), None
    url = source if source.startswith('https://') else 'https://i.imgur.com/' + source
    for attempt in range(2):
        try:
            request = urllib.request.Request(url, headers={'User-Agent': 'Mozilla/5.0'})
            with urllib.request.urlopen(request, timeout=18) as response:
                if not response.headers.get('Content-Type', '').startswith('image/') or 'removed' in response.url:
                    return source, None, 'unavailable'
                data = response.read(15 * 1024 * 1024)
            with tempfile.NamedTemporaryFile(suffix=Path(source).suffix) as original:
                original.write(data)
                original.flush()
                info = subprocess.run(['sips', '-g', 'pixelWidth', '-g', 'pixelHeight', original.name], capture_output=True, text=True)
                dimensions = [int(line.split(':')[1]) for line in info.stdout.splitlines() if 'pixelWidth:' in line or 'pixelHeight:' in line]
                if len(dimensions) != 2 or dimensions[0] < 180 and dimensions[1] < 100:
                    return source, None, 'placeholder or invalid image'
                converted = subprocess.run(['sips', '-Z', '640', '-s', 'format', 'jpeg', '-s', 'formatOptions', '75', original.name, '--out', str(destination)], capture_output=True)
                if converted.returncode:
                    destination.unlink(missing_ok=True)
                    return source, None, 'conversion failed'
            return source, destination.relative_to(root).as_posix(), None
        except Exception as error:
            if attempt:
                return source, None, type(error).__name__
            time.sleep(1)

manifest, failures = {}, []
with ThreadPoolExecutor(max_workers=8) as pool:
    futures = [pool.submit(cache, source) for source in sources]
    for index, future in enumerate(as_completed(futures), 1):
        source, path, error = future.result()
        if path:
            manifest[source] = path
        else:
            failures.append({'source': source, 'reason': error})
        if index % 100 == 0:
            print(f'{index}/{len(sources)} checked; {len(manifest)} cached', flush=True)
(root / 'src/js/photo-cache.js').write_text('/* Existing catalog photos, served locally. Generated by scripts/cache_photos.py. */\nconst photoCache = ' + json.dumps(manifest, indent=2) + ';\n')
Path('/tmp/bias-photo-failures.json').write_text(json.dumps(failures, indent=2))
print(f'Finished: {len(manifest)} cached, {len(failures)} unavailable.', flush=True)
